spring.application.name=coreservices
jwt.secret=inventorymonitoringsystemsecretkeyforjwtdemo
jwt.expiration-ms=86400000

# PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=Irctc@11

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port Number
server.port=8001

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
